### ISSUE TITLE
Remove unnecessary attribute in SceneLineItemBlock "value"

### ISSUE THREAD

**Issue by benneti** [ricklupton/rmscene#13]
I am not sure whether I am the problem or I misunderstood something, but while trying to include rmscene into rmrl (see https://github.com/benneti/rmrl ), I stumbled upon the problem that it is not possible to access block.value but only block.item.value.
But looking at the code (as someone unfamiliar with `@dataclass` notation) it looks like there should be a value optional available directly.
Some more insight would be appreciated!

**Comment by ricklupton** [comment]
Hi,

I think this is a mistake by me, in ad592adc1524b941814f95e656f1b85b75f76a3f I changed to using block.item, but did not remove all the old value attributes. Using block.item.value is the right way. 

I would anyway recommend using the “scene tree” interface, since it will handle the tree structure, nesting, layers etc. See for example the code in https://github.com/ricklupton/rmc/blob/scene-tree/src/rmc/exporters/svg.py

**Comment by benneti** [comment]
Ah, thanks for the reply, this makes sense. I think the rmscene part is already working but transforming I do not yet understand how to correctly transform to fit it ontop of a potential base pdf.

**Comment by ricklupton** [comment]
Fixed in 15c4964afdcf0b2dc85a005253e1954b42d3a609
