### ISSUE TITLE
Better error handling within blocks

### ISSUE THREAD

**Issue by ricklupton** [ricklupton/rmscene#18]
Currently any parsing error aborts parsing the whole file, but we should be able to skip to the next block and try again. Reporting the location in the file where the error happened would be useful for diagnosing the problem too (e.g. in #17)

In [`_read_blocks`](https://github.com/ricklupton/rmscene/blob/main/src/rmscene/scene_stream.py#L695-L714), the `yield block_type.from_stream(stream)` can be wrapped in a try/except.

**Comment by Azeirah** [comment]
So far I've had two scenarios with block parsing causing an Exception. The first was because the format is different under certain circumstances, the second is possibly corrupt.

Despite these exceptions, all of the other blocks in both files were parsed and read correctly, so yes, it makes a lot of sense to simply skip the block and instead log an error when block exceptions are encountered.

**Comment by ricklupton** [comment]
Closed by 74e359ad415c6e18b0217324d827ee74564aac2f
